// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: boards.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, events, created_at, updated_at, game_id, owner_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, events, created_at, updated_at, game_id, owner_id
`

type CreateBoardParams struct {
	ID        uuid.UUID
	Events    json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	GameID    uuid.UUID
	OwnerID   string
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard,
		arg.ID,
		arg.Events,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.GameID,
		arg.OwnerID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GameID,
		&i.OwnerID,
	)
	return i, err
}

const getUserBoards = `-- name: GetUserBoards :many
SELECT id, events, created_at, updated_at, game_id, owner_id FROM boards WHERE owner_id = $1
`

func (q *Queries) GetUserBoards(ctx context.Context, ownerID string) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, getUserBoards, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GameID,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
