// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID        uuid.UUID
	Events    json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	GameID    uuid.UUID
	OwnerID   string
}

type Game struct {
	ID        uuid.UUID
	Name      string
	EndTime   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	Preset    uuid.UUID
	AdminID   string
}

type GamesUser struct {
	ID        uuid.UUID
	GameID    uuid.UUID
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Preset struct {
	ID        uuid.UUID
	Name      string
	Events    json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	OwnerID   string
}

type User struct {
	ID         string
	Nickname   string
	PublicID   string
	Email      string
	PictureUrl string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
