// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, nickname, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, nickname, created_at, updated_at, token
`

type CreateUserParams struct {
	ID        uuid.UUID
	Nickname  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Nickname,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT id, nickname, created_at, updated_at, token FROM users WHERE token = $1
`

func (q *Queries) GetUserByToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
	)
	return i, err
}
